module.exports = {
  name: "",
  version: "1.0.0",
  main: "index.ts",
  author: "Created with create-app <https://github.com/jmmaraujo55/create-app>",
  license: "MIT",
  scripts: {
    build: "rimraf ./dist && tsc",
    dev: "nodemon",
    start: "node -r ts-node/register -r tsconfig-paths/register dist/index.js",
    format: 'prettier --write "**/*.ts"',
  },
  dependencies: {
    colors: "1.4.0",
    luxon: "^3.0.1",
    rimraf: "^3.0.2",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.1.0",
    typescript: "^4.7.4",
    dotenv: "^16.0.1",
  },
  devDependencies: {
    "@types/node": "^18.6.4",
    "@typescript-eslint/eslint-plugin": "^5.32.0",
    "@typescript-eslint/parser": "^5.32.0",
    eslint: "^8.21.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^3.4.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.2.1",
    husky: "^8.0.1",
    nodemon: "^2.0.19",
    prettier: "^2.7.1",
  },
};
